gnoverse/dsocial

README.md
realm/gno.mod
realm/post.gno
realm/public.gno
realm/render.gno
realm/social.gno
realm/userposts.gno
realm/util.gno

This code imitates the boards realm. It allows calling PostMessage, PostReply and viewing it in a browser. See the README.

chore: Initial realm with PostMessage + README

---

mobile/app/(auth)/import-account.tsx
mobile/app/(auth)/landing.tsx
mobile/app/(auth)/sign-up.tsx
mobile/app/(root)/settings.tsx
mobile/app/_layout.tsx
mobile/components/auth/index.tsx
mobile/context/auth/index.tsx
mobile/package.json
mobile/redux/features/accountSlice.ts
mobile/redux/index.ts
mobile/redux/store.ts
mobile/tsconfig.json
mobile/types.ts
mobile/yarn.lock

This pull request adds the Redux framework to the project, including the necessary files and dependencies.

Add Redux framework

---

README.md
mobile/app/(auth)/import-account.tsx
mobile/app/(auth)/landing.tsx
mobile/app/(auth)/sign-up.tsx
mobile/app/(root)/home.tsx
mobile/app/(root)/post.tsx
mobile/app/(root)/settings.tsx
mobile/app/settings/remove-account/confirm.tsx
mobile/app/settings/remove-account/index.tsx
mobile/components/button/link.tsx
mobile/components/loading/index.tsx
mobile/components/loading/loading-modal.tsx
mobile/components/loading/loading.tsx
mobile/src/hooks/use-gno.ts
mobile/src/hooks/use-onboarding.ts

This PR introduces the Register User journey for GnoSocial.
During registration, the code checks the address on the Blockchain, provides some coins and registers the account if necessary.

Register user

---

realm/post.gno
realm/public.gno
realm/render.gno
realm/userposts.gno
realm/util.gno

Add support for following other users and showing on the home screen. This PR has four commits. The first three small commits are:
1. In `displayAddressMD`, link to the user's r/berty/social page (not the simple r/demo/users page).
2. There is already a function `getUserPosts` to get the `UserPosts` object. For consistency, also use it in `Render`.
3. In Post.MarshalJSON, add field for creator. (Previously, this wasn't necessary, but now the posts returned in the JSON are a mixture of posts from different users.)
In the third commit:
* In the `UserPosts` struct, add `followers` and `following`, and related methods `Follow` and `Unfollow`.
* In public.gno, add the top-level functions `Follow` and `Unfollow`.
* In `UserPosts` add `RenderFollowers` and `RenderFollowing`. Update the main …

chore: Support following other users

---

realm/public.gno

As we discussed, a helper function.

chore: Add GetHomePostsCount to help with GetHomePosts

---

realm/public.gno
realm/userposts.gno

Add JSON helper functions for following.
* In UserPosts, add `MarshalJSON`.
* Use this to add `GetJsonUserPostsInfo`.
* Also add `GetJsonFollowers` and `GetJsonFollowing`
Tested `GetJsonUserPostsInfo` in the GnoSoclal demo app with the following code:
```
const result = await gno.qEval("gno.land/r/berty/social", `GetJsonUserPostsInfo("g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5")`);
if (!(result.startsWith('(') && result.endsWith(' string)'))) throw new Error("Malformed GetJsonUserPostsInfo response");
const quoted = result.substring(1, result.length - ' string)'.length);
const json = JSON.parse(quoted);
const info = JSON.parse(json);
```
Example value of `json`:
```
{"address": "g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5", "url": "/r/berty/social:test_1", "n_threads": 3, "n_followers": 2, …
```

chore: Add GetJsonUserPostsInfo, GetJsonFollowers and GetJsonFollowing

---

mobile/Makefile
mobile/app.json
mobile/app/home/feed.tsx
mobile/app/home/search/index.tsx
mobile/app/index.tsx
mobile/assets/styles/colors.ts
mobile/components/icons/Search.tsx
mobile/components/list/search/search-box.tsx
mobile/components/list/search/search-empty-list.tsx
mobile/components/list/search/search-item.tsx
mobile/components/list/search/search-result-list.tsx
mobile/components/view/feed/index.tsx
mobile/ios/gnosocial/Info.plist
mobile/src/hooks/use-feed.ts
mobile/src/hooks/use-search.ts

This PR adds two things:
1.  search for users feature
Adds a new page at mobile/app/home/search.
2. improves the home feed by inversing the fetching indexes
It now users 'GetHomePostsCount' to calculate the indexes that will be used to fetch the posts.

feat: search users and inverse home feed

---

mobile/app/sign-in.tsx
mobile/app/sign-up.tsx
mobile/components/textinput/index.tsx

This PR fix the issue #54 by cleaning the inputs on the sign-in page (import seed phrase". It also set the focus on the first text input of each screen.

chore: clean input fields

---

mobile/src/hooks/use-search.ts

fix: In use-search, remove unneeded send amount for Follow/Unfollow

---

mobile/app/[account]/index.tsx
mobile/app/home/feed.tsx
mobile/app/post/[post_id].tsx
mobile/components/layout/body.tsx
mobile/components/view/account/index.tsx
mobile/components/view/feed/feed-view.tsx
mobile/components/view/feed/index.tsx
mobile/components/view/index.ts
mobile/redux/features/replySlice.ts
mobile/src/hooks/use-feed.ts

This PR adds a feed component to the profile page.
It also fixes an issue that occurs when the user tries to replay a post.

feat: post feed into user profile

---

mobile/app/[account]/index.tsx
mobile/app/home/feed.tsx
mobile/app/post/[post_id].tsx
mobile/components/view/account/index.tsx
mobile/components/view/feed/feed-view.tsx
mobile/redux/features/replySlice.ts

This pull request refactors the code related to posting a reply from the feed and user profile. 
It includes changes to the `FeedView` component, the `AccountView` component, and the `replySlice` module. 
The changes ensure that the correct post is set as the post to reply to and navigate to the correct post page when a post is pressed.

feat: reply to a post

---

mobile/app/post/[post_id].tsx

Add KeyboardAvoidingView for reply input in post page

fix: keyboard over textinput

---

mobile/src/hooks/use-feed.ts

fix: display repost

---

mobile/Makefile
mobile/app.json
mobile/app/index.tsx
mobile/components/settings/account/account-balance.tsx
mobile/package-lock.json
mobile/package.json

feat: display version number

---

mobile/app/home/feed.tsx
mobile/components/feed/gnod-label.tsx
mobile/components/feed/repost-button.tsx
mobile/components/feed/tweet.tsx

In this PR we'll concentrate the Gnods in the original Post.
fix #101

feat: gnod the original post

---

mobile/components/feed/gnod-label.tsx
mobile/components/feed/repost-button.tsx
mobile/components/feed/repost-label.tsx
mobile/components/feed/tweet-repost.tsx
mobile/components/feed/tweet.tsx
mobile/src/hooks/use-feed.ts
mobile/types.ts

Standardizing main post verification.

refactor: checking parent post

---

mobile/app/[account]/remove.tsx
mobile/app/_layout.tsx
mobile/app/home/feed.tsx
mobile/app/home/profile.tsx
mobile/app/index.tsx
mobile/app/post/[post_id].tsx
mobile/app/post/index.tsx
mobile/app/repost/index.tsx
mobile/app/sign-up.tsx
mobile/components/modal/reenter-password.tsx
mobile/components/settings/account/account-balance.tsx
mobile/package-lock.json
mobile/package.json
mobile/redux/index.ts
mobile/redux/redux-provider.tsx
mobile/src/hooks/use-feed.ts
mobile/src/hooks/use-onboarding.ts
mobile/src/hooks/use-search.ts
mobile/src/hooks/use-user-cache.ts

chore: upgrading gnonative expo library

---

mobile/app/sign-up.tsx

This helps make sure that Register with r/demo/users will succeed.

chore: In the sign-up name check, use the same regex and error message as r/demo/users

---

mobile/app/[account]/index.tsx
mobile/app/home/feed.tsx
mobile/components/feed/post-content-label.tsx
mobile/components/feed/post-row.tsx
mobile/components/layout/header.tsx
mobile/components/view/account/index.tsx
mobile/components/view/account/no-account-view.tsx
mobile/package-lock.json
mobile/package.json

feat: Add mentions on text renderer

feat: Add mentions on text renderer"

---

mobile/app/index.tsx
mobile/app/sign-up.tsx
mobile/redux/features/accountSlice.ts
mobile/redux/redux-provider.tsx

This PR exposes GnoNative API in Redux.
It will be useful for creating complex business logics that consumes the API into the application.

refactor: consuming the api from redux

---

mobile/Makefile
mobile/README.md
mobile/app.json
mobile/package-lock.json

chore: manual release process + npm audit fix

---

mobile/app/[account]/index.tsx
mobile/components/view/account/index.tsx

fix: display profile picture

---

mobile/redux/features/linkingSlice.ts

Enhance the URL and redirection builder for improved readability and maintainability. This change simplifies the construction of URLs by utilizing the URL API, making the code cleaner and easier to understand.

refactor: URL and redirection handling

---

README.md
mobile/README.md

Minor update to make the Markdown editor happy.

readme update

---

.releaserc

Change the semantic release configuration for extra-plugins.

fix: semantic release config
