README.md
Instead of the gnofaucet in the main repo, there is a new faucet at https://github.com/gnolang/faucet . Change the README to use this.
=> chore: In README, change to use the new gnolang/faucet

realm/post.gno, realm/public.gno, realm/render.gno, realm/social.gno, realm/userposts.gno, realm/util.gno
The Effective Gno document says ["Your package name should match the folder name."](https://github.com/gnolang/gno/blob/71b2e762b97887981d91d46d682cce2960b97c20/docs/how-to-guides/effective-gno.md?plain=1#L318) Our folder name is "social" and the import path is "r/berty/social"
Therefore, this PR renames `package gnosocial` to `package social`. (Note that the boards realm [just uses `package boards`](https://github.com/gnolang/gno/blob/f6698e6aeb2919771a058b99c07ac9b9e0b7a4bd/examples/gno.land/r/demo/boards/post.gno#L1).)
=> chore: Rename the package from gnosocial to social

realm/post.gno, realm/public.gno
Add public function GetThreadPosts with supporting private functions. Example response:
```
{"n_threads": 2, "posts": [
{"index": 0, "post": {"id": 1, "createdAt": "2024-02-15T17:37:28Z", "n_replies": 3, "n_replies_all": 5, "parent_id": 0, "body": "My second post"}},
{"index": 1, "post": {"id": 3, "createdAt": "2024-02-15T17:37:28Z", "n_replies": 0, "n_replies_all": 0, "parent_id": 0, "body": "My third post"}}]}
```
=> Add GetThreadPosts with JSON response

realm/render.gno
With this change, the main GnoSocial page at (for example) http://testnet.gno.berty.io/r/berty/social looks like the following, where the user names are links to their GnoSocial page:
```
Welcome to GnoSocial!
jefft0
test_1
```
=> Chore: List users on main GnoSocial render page

mobile/app/(root)/settings.tsx, mobile/components/settings/account/account-balance.tsx, mobile/components/settings/index.ts
This pull request adds a new feature to display the account balance. It includes changes to the `Config` page, adding the `AccountBalance` component, and updating the UI to show the active account's name, address, and balance.
=> Display account balance

realm/public.gno
Add public function `GetUsers` which returns an avl.Tree of users. See the function doc comment. Also add `GetJsonUsers` which returns the result as JSON. Tested in the GnoSoclal demo app with the following code:
```
const result = await gno.qEval('gno.land/r/berty/social', 'GetJsonUsers()');
if (!(result.startsWith('(') && result.endsWith(' string)'))) throw new Error("Malformed GetThreadPosts response");
const quoted = result.substring(1, result.length - ' string)'.length);
const json = JSON.parse(quoted);
const users = JSON.parse(json);
```
Example value of `json`:
```
{"n_users": 2, "users": [
{"name": "jefft0", "address": "g1juz2yxmdsa6audkp6ep9vfv80c8p5u76e03vvh"},
{"name": "test_1", "address": "g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5"}]}
```
=> chore: Add GetUsers with JSON response

mobile/app/(root)/post.tsx
This pull request fixes the gasWanted value in the PostMessage function in order to set it to 10,000,000 instead of 2,000,000. This ensures that the function has enough gas to execute properly.
=> Fix gasWanted value in PostMessage function

realm/public.gno, realm/social.gno, realm/userposts.gno
In the current `GetJsonHomePosts`, [a comment](https://github.com/gnolang/gnosocial/blob/7348d269c00e89829180cf039c8d5f30d1663671/realm/public.gno#L216-L217) points out that there can be multiple posts with the same timestamp. This can be resolved if the Post ID is globally unique for the whole GnoSocial realm. (Currently, the post ID is only unique for each user.) This PR implements this with two commits:
1. Move `postsCtr` from the `UserPosts` object to a global variable for the realm.
2. Now, we can simplify the avl.Tree in `GetHomePosts` and the related `addFollowedPosts`. The avl.Tree key is postTime/postID. Because the postID is globally unique, this creates a unique key even if the postTime is the same for multiple posts. The keys are still sorted by postTime. The problem mentioned …
=> chore: Use global postsCtr to help sorting by timestamp

realm/public.gno, realm/render.gno, realm/userposts.gno, realm/util.gno
As explained in [this comment](https://github.com/gnolang/gno/pull/1433#issuecomment-1973049786), a recent PR makes a breaking change to the API for r/demo/users. This PR updates r/berty/social to use the new API. This is necessary if you install the latest gnodev with the new API.
=> fix: Access the User struct Name and Address without the getter method

realm/public.gno, realm/util.gno
This is a follow-up to PR #34 which added `GetJsonUserByAddress`.
GnoSocial needs the information from `users.GetUserByName`, but calling this remotely returns the usual result that's difficult to process. This PR adds the utility function `GetJsonUserByName` to return the `User` object as JSON. We can remove this when Gno.land is updated to return usable objects  for remote function calls.
This PR has two commits:
1. Refactor the existing `GetJsonUserByAddress` to add the utility function `marshalJsonUser`.
2. Add `GetJsonUserByName` which also uses `marshalJsonUser`.
Tested in the GnoSoclal demo app with the following code:
```
const result = await gno.qEval("gno.land/r/berty/social", `GetJsonUserByName("test_1")`);
if (!(result.startsWith('(') && result.endsWith(' string)'))) throw new …
```
=> chore: Add GetJsonUserByName

mobile/.tool-versions, mobile/Makefile, mobile/README.md
Similar to gnonative, in the gnosocial/mobile README, add instructions to install asdf and Android Studio.
=> chore: Add .tool-versions, asdf instructions

realm/post.gno, realm/public.gno, realm/userposts.gno
From a code review by @D4ryl00, this PR fixes:
1. In `newUserPosts`, initialize fields followers and following.
2. In `GetReply`, rename the Post object from `thread` to `post` (to be consistent with the other methods).
3. In 'RepostThread`, move the check for `userPostsAddr == caller` earlier. (Fail as early as possible to save CPU.)
=> fix: From code review, fix newUserPosts, GetReply and RepostThread

README.md, mobile/src/hooks/use-gno.ts
A [recent commit](https://github.com/gnolang/gno/blame/01e91be7bbde8e9cfc2069f66f24bc83d677103a/contribs/gnodev/main.go#L54) updates gnodev to use the chain ID "dev". When gnodev is updated locally or on the Berty test node, it needs to use this chain ID. So, this PR renames "tendermint_test" to "dev".
=> chore: Rename chain ID tendermint_test to dev

realm/post.gno, realm/public.gno, realm/userposts.gno
Currently, `GetHomePosts` computes the home posts (including all followed posts) each time it is called. This is necessary because we want to call it with QEval (no gas fee) which can't update the realm data to save the result. But this is not scalable.  This PR solves the problem by saving the state of the home posts. This is returned by `GetHomePosts`, but we add a separate `RefreshHomePosts` which is requires gas and adds the followed posts since the last call.
* In a first minor commit, fix comments because the type `Post.id` should be `PostID`
* In `UserPosts`, add the avl.Tree `homePosts` which saves the state of the home posts. In `GetHomePosts`, simply return this avl.Tree.
* Update `RenderUserPosts` to use the current state of `homePosts` (if viewing the home feed). Also add a …
=> Chore: Save the state of home posts and add RefreshHomePosts

realm/userposts.gno
UserPosts `Follow` [updates the `following` avl.Tree](https://github.com/gnolang/gnosocial/blob/bf135e41a0f5328ea29d8024a46327d2419822dc/realm/userposts.gno#L78-L81) with a `FollowingInfo` structure which includes the followed user's latest post ID. This is so that the home posts only include posts of another user after starting to follow them. Normally, `Follow` is only called once to follow another user. The problem is that if it is called a second time, then it will update with a new `FollowingInfo` which replaces the previous one. This could result in to showing some followed posts which were made after the initial call to `Follow`.
This PR solves this problem by checking if the other user is already being followed. If yes, then do nothing.
=> chore: In UserPosts.Follow, do nothing if already following

mobile/README.md
Tested the instructions for `make ios` in mobile/README on a macOS 14 virtual machine, so add this in the README. Remove unsupported macOS 12.
=> chore: mobile/README: Add macOS 14. Remove macOS 12

.gitattributes
Add the [same .gitattributes](https://github.com/gnolang/gno/blob/d44c9a5dcd28c5800c9529f47be168f38ebb0ffa/.gitattributes#L1) for gno syntax highlighting as in gno.
=> chore: Add .gitattributes for gno syntax highlighting

realm/public.gno
If the avl.Tree for followers and following has more than about 1000 entries, then it takes too much gas to iterate it. So, similar to `GetJsonHomePosts`, in `GetJsonFollowers` and `GetJsonFollowing` we add a start and end index.
BREAKING CHANGES:
* In `GetJsonFollowers` and `GetJsonFollowing`, add params `startIndex` and `endIndex`.
* In the returned JSON string of `GetJsonFollowers`, add `n_followers`. (See example below.)
* In the returned JSON string of `GetJsonFollowing`, add `n_following`. (See example below.)
Tested `GetJsonFollowers` in the GnoSoclal demo app with the following code:
```
const result = await gno.qEval("gno.land/r/berty/social", `GetJsonFollowers("g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5", 0, 100)`);
if (!(result.startsWith('(') && result.endsWith(' string)'))) …
```
=> chore: In GetJsonFollowers and GetJsonFollowing, add start and end index

mobile/app/[account]/_layout.tsx, mobile/app/[account]/remove.tsx, mobile/app/home/profile.tsx, mobile/components/view/account/remove-account.tsx/index.tsx
This PR fixes the remove account button by implementing a new router and calling the gnokey deleteAccount function.
=> fix: remove account button

realm/public.gno
We already have [`GetThreadPosts`](https://github.com/gnolang/dsocial/blob/faf388890cdff5f43e81680777b5d6ca891b9ec5/realm/public.gno#L91-L100) which is good to use an index range to get the posts in-order of a thread (or reply thread). But the home feed includes followed posts inserted at any point in the feed. We need a way to get arbitrary top-level posts by Post ID. This PR adds `GetJsonTopPostsByID`.
Tested in the GnoSoclal demo app with the following code:
```
const result = await gno.qEval("gno.land/r/berty/social", "GetJsonTopPostsByID([]UserAndPostID{" + 
`{"g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5", 1}, ` + 
`{"g1jg8mtutu9khhfwc4nxmuhcpftf0pajdhfvsqf5", 3}, ` + "})");
if (!(result.startsWith('(') && result.endsWith(' string)'))) throw new Error("Malformed GetJsonTopPostsByID …
```
=> chore: Add GetJsonTopPostsByID

realm/public.gno, realm/userposts.gno
When `Follow` creates the `FollowingInfo`, it [sets `startedPostsCtr`](https://github.com/gnolang/dsocial/blob/3cef6166d556b6119b5d7da7e9b49d4aadef1941/realm/userposts.gno#L86) to the current value of the global posts counter. This is used when computing the user's home posts to only show the posts of a followed user after starting to follow. In the indexer, we want to scan the transactions for calls to `Follow` to make a copy of the list of users being followed, so the indexer needs to know the value of `startedPostsCtr`. Because it is returned from `Follow`, the indexer can look at the transaction result.
=> chore: In Follow, return the value of startedPostsCtr in the added FollowingInfo

mobile/README.md
Ubuntu 24.04 has been released. Also, the latest Android Studio is Jellyfish. I tested the README instructions in fresh Ubuntu and macOS virtual machines.
* Include Ubuntu 24.04 in the supported versions
* Change to the latest tested Android Studio, Jellyfish
* Ubuntu 24.04 doesn't come with `make`, so add it to the install list
=> chore: In README, change to Jellyfish, add Ubuntu 24.04

mobile/src/hooks/use-search.ts
If the user has already posted, then the user already has a dSocial user entry, and clicking on Follow just adds the Follow information. But if it is a new account, clicking on Follow also creates the dSocial user entry. This requires more gas. Therefore, this PR increases the gasWanted for Follow so that it doesn't fail in this case. (Also increase the gasWanted for Unfollow for symmetry.)
=> fix: In call to Follow, increase gasWanted

realm/public.gno
The r/berty/social code is based on r/demo/boards which uses `std.AssertOriginCall()` . As explained in https://github.com/gnolang/gno/issues/1576, `AssertOriginCall` is scheduled to be removed from the `std` package. On the dev call they mentioned that it will also be removed from r/demo/boards as unnecessary. Therefore, this PR removes `std.AssertOriginCall()` . Removing it now avoids a future breaking change when it is removed from the `std` package.
=> chore: Remove deprecated std.AssertOriginCall()

mobile/app/home/search/index.tsx, mobile/src/hooks/use-search.ts
In the search screen, set the param to true so that the search result doesn't have the user's own name. Resolves https://github.com/gnolang/dsocial/issues/65 .
=> chore: In searchUser, add optional param excludeActiveAccount

realm/post.gno, realm/userposts.gno
* fix a bug in refreshHomePosts for updating `startKey`. (This was caught by the new lint operation when gnodev loads the realm code.)
* In the web page Render, show posts and replies in reverse order, like the dSocial app.
=> chore: Render posts in reverse order, fix a small bug

realm/post.gno, realm/public.gno, realm/util.gno
Add realm support for reactions:
* Add type Reaction and conts "enum" for the reaction types. Currently the only Reaction is `Gnod`.
* In Post, add an avl.Tree for `reactions` where the key is the `Reaction` and the value is the set of user addresses.
* In Post, add methods `AddReaction`, `RemoveReaction` and `GetReactionCount`.
* In Post `MarshalJSON`, include `n_gnods`.
* Add public API functions `AddReaction` and `RemoveReaction`.
* Update the web page Render to show the count of gnods, an a button to add a gnod.
=> chore: Add reactions support

tools/indexer-service/graphql_client.go
A recent gno commit changed the realm call response from "(1 gno.land/r/berty/social.PostID)" to "(1 gno.land/r/berty/social.PostID)\n\n". Therefore, we need to trim ending whitespace before parsing.
=> chore: indexer-service: In getPostID, trim whitespace before parsing

mobile/app/[account]/index.tsx
[account] `fetchData` calls `setTotalPosts`. Currently, it calls `feed.fetchCount` which is for the current user's home feed. But this is also used to display another user's profile. This PR checks `currentUser.address` and if it is not for the current user then it calls `feed.fetchThreadPosts` to get the count of the other user's top-level threads.
(Note that this also makes it independent of the dSocial indexer, so that it's possible to view another user's posts when the indexer is down.)
=> fix: In [account] fetchData, set totalPosts with fetchThreadPosts for other user

.github/workflows/release.yml, .releaserc, mobile/.gitignore, mobile/Makefile, mobile/app.config.js, mobile/app.json, mobile/app/_layout.tsx, mobile/eas.json, mobile/package-lock.json, mobile/package.json, mobile/src/grpc/transport_web.ts
This PR fixes the ability to fetch the Expo push token by removing the global polyfill of `fetch` in React-Native. The polyfill fetch version is not polyfill globally anymore, but is used only for the Connect transport to support streaming capabilities.
This PR also fixes the EAS configuration to require the google-service.json file (and GoogleService-info.plist) in production environment only. So It will be easier for development purposes to compile dSocial.
To locally compile the app in production mode (to test push notifications for example, set the environment variables:
```
GOOGLE_SERVICES_JSON=/Users/remi/dsocial/mobile/google-services.json MY_ENVIRONMENT=production npx expo run:android
GOOGLESERVICES_INFO_PLIST=/Users/remi/dsocial/mobile/GoogleService-Info.plist …
```
=> fix: get push token + EAS build

mobile/app.json
With this PR I'd expect not having to press that Apple button (Export Compliance Information) on every release to TestFligth.
Reference:
https://docs.expo.dev/versions/latest/sdk/securestore/#exempting-encryption-prompt
Signed-off-by: Iuri Pereira 689440+iuricmp@users.noreply.github.com
=> chore: avoiding Apple Export Compliance Information on TestFlight

mobile/Makefile, mobile/app/_layout.tsx, mobile/components/change-network/network-list-item/index.tsx, mobile/components/change-network/network-list/index.tsx, mobile/components/feed/post-row.tsx, mobile/components/feed/repost-row.tsx, mobile/components/list/account/account-item.tsx, mobile/redux/features/signupSlice.ts, mobile/src/grpc/transport_web.ts, mobile/types.ts
We want to use `npm run ts:check` in the Makefile, but first we must resolve the errors. This PR has five commits:
1. The `process.env` object is created dynamically, so ignore errors for undefined values such as `EXPO_PUBLIC_GNO_REMOTE`.
2. In types.ts, add `NetworkMetainfo` and `GnoAccount`. Correct the import to use `@gno/types`.
3. In transport_web, it complains that "Could not find a declaration file" for imported packages react-native-polyfill-globals and react-native-fetch-api. We can't change the imported packages, so ignore these errors.
4. In transport_web, add the "any" declaration to `forEach((value:any, key:any)`.
5. Now that the errors are fixed, we can update the Makefile. Add a target ts_check to do `npm run ts:check`. Add this as a dependency to the node_modules target, …
=> chore: Resolve ts:check errors, put in Makefile

realm/public.gno
PR https://github.com/gnolang/gno/pull/1708 has been merged which has `avlhelpers.ListByteStringKeysByPrefix`. In public.gno, remove the temporary copy of this function and make `ListUsersByPrefix` use the "official" `avlhelpers.ListByteStringKeysByPrefix`.
NOTE: If the Berty node updates dsocial, then its gnodev needs to be using the latest gno repo which has `avlhelpers.ListByteStringKeysByPrefix`.
=> chore: Make ListUsersByPrefix use avlhelpers.ListByteStringKeysByPrefix

mobile/Makefile
In mobile/Makefile, we want to run ts_check for most build targets. Most build targets use node_modules, so we put ts_check as a dependency of the node_modules target. But this makes ts_check run before `npm install`. This doesn't work because ts_check needs `npm install` to run first in order to install tsc.
This pull request removes ts_check for the dependency of node_modules and adds it explicitly to the dependencies of build targets _after_ node_modules.
=> chore: In mobile/Makefile, use ts_check after node_modules

mobile/app/home/profile.tsx, mobile/redux/features/accountSlice.ts
Please, see the description at https://github.com/gnolang/gnokey-mobile/pull/18
=> feat: universal login

realm/post.gno, realm/userposts.gno
PR https://github.com/gnolang/gno/pull/2887 introduced the helper function `txlink.URL` to format the URL "help" screen for the gnokey command. It also updated r/demo/boards to use it. In dSocial, we have a similar need. This PR updates the realm code to use `txlink.URL` . As an advantage, this is future proofing against changes to the "help" screen, as happened a few weeks ago in PR https://github.com/gnolang/gno/pull/2876 . Without using `txlink.URL`, those are breaking changes.
=> fix: In realm code, use txlink.URL

mobile/redux/features/linkingSlice.ts
Following Gnokey Mobile PR https://github.com/gnolang/gnokey-mobile/pull/22, rename comms URL "tologin" to "tosignin".
=> chore: In comms URL, rename tologin to tosignin

mobile/app.config.js, mobile/eas.json
In `app.config.js`, we want that `GoogleService-Info.plist` and `GoogleService-Info.plist` can be optional for the CI, and only use them locally by setting the `local-production` profile
=> chore: make the google auth file optional with new EAS profile

realm/post.gno, realm/userposts.gno
This is a follow-up to PR https://github.com/gnoverse/dsocial/pull/138 where we changed the realm code to use `txlink.URL`. Now, in the breaking change of PR https://github.com/gnolang/gno/pull/3289 this was renamed to `txlink.Call` . As show in the [changes to r/demo/boards,](https://github.com/gnolang/gno/pull/3289/files#diff-4b154b6eeb8243a0d18b7211540bcff8bc22d4fd0de567c9f77804b53423d8ed) all we have to do is rename.
=> fix: Change txlink.URL to txlink.Call

realm/gno.mod
There is a breaking change (for the better) in PR https://github.com/gnolang/gno/pull/3123 which removes the useless `require` statement from `gno.mod` . That PR [updated `gno.mod`](https://github.com/gnolang/gno/pull/3123/files#diff-0b555c4db5d3502bf36327c922783d40fec73107b42c7cd69656b374e2a3f5dd) in many realms. This PR does the same to remove `require` from our `gno.mod`.
=> fix: In gno.mod, remove require

realm/public.gno
A [recent gno PR](https://github.com/gnolang/gno/pull/3377/files#diff-a294482bc80501435f316c1256e53b17f30307d652ca7327389197d14fe04569) has a breaking change to make `ListByteStringKeysByPrefix` use the new `avl.ITree` interface. As shown in that PR's [update to users.go](https://github.com/gnolang/gno/pull/3377/files#diff-06fa8b65268e852f436005d01a174bd6ca9915524438e1effffeccfe02e9a543), it's necessary to pass the address of the tree when calling `ListByteStringKeysByPrefix`. This PR does the same thing in dsocial.
=> fix: In ListUsersByPrefix, pass the address of the tree to ListByteStringKeysByPrefix

mobile/redux/features/accountSlice.ts, realm/public.gno, realm/render.gno, realm/userposts.gno, realm/util.gno
This PR update dsocial with the latest gno version.
So the dsocial realm:
- uses latest std functions (OriginCaller() instead of GetOriginCaller)
- uses the new `users` realm.
The mobile version is also updated to use the new `users` realm API.
=> Feat: use latest std + users realm

README.md
Update the README:
* Run gnodev in the gno repo so that it has the correct Go version
* Update the gnodev localhost port to 26657
* Increase gas-wanted
* Use the new users realm `gno.land/r/gnoland/users/v1`
* Make the username conform to the new users realm (end in three digits)
=> chore: Update README to the latest gno repo requirements

mobile/redux/features/linkingSlice.ts
The latest Gnokey Mobile version (https://github.com/gnolang/gnokey-mobile/pull/42) estimates the gas used for a transaction and can update the transaction with the GasWanted recommended value in the `update_tx` parameter is set in the deeplink.
So this PR adds this parameter.
=> feat: tell gnokey mobile to update GasWanted field

mobile/package-lock.json, mobile/package.json
As explained in https://github.com/gnolang/gnonative/pull/215, we updated Gno Native Kit to fix some breaking changes. This made new [gnonative NPM package version 4.7.2](https://www.npmjs.com/package/@gnolang/gnonative/v/4.7.2). Therefore, we update dSocial to use it.
=> fix: Use gnonative 4.7.2
